const flagBaseUrl = "https://flagcdn.com/256x192/";
const currencyFlags = {
    AUD: `${flagBaseUrl}au.png`,
    BGN: `${flagBaseUrl}bg.png`,
    BRL: `${flagBaseUrl}br.png`,
    CAD: `${flagBaseUrl}ca.png`,
    CHF: `${flagBaseUrl}ch.png`,
    CNY: `${flagBaseUrl}cn.png`,
    CZK: `${flagBaseUrl}cz.png`,
    DKK: `${flagBaseUrl}dk.png`,
    GBP: `${flagBaseUrl}gb.png`,
    HKD: `${flagBaseUrl}hk.png`,
    HUF: `${flagBaseUrl}hu.png`,
    IDR: `${flagBaseUrl}id.png`,
    ILS: `${flagBaseUrl}il.png`,
    INR: `${flagBaseUrl}in.png`,
    ISK: `${flagBaseUrl}is.png`,
    JPY: `${flagBaseUrl}jp.png`,
    KRW: `${flagBaseUrl}kr.png`,
    MXN: `${flagBaseUrl}mx.png`,
    MYR: `${flagBaseUrl}my.png`,
    NOK: `${flagBaseUrl}no.png`,
    NZD: `${flagBaseUrl}nz.png`,
    PHP: `${flagBaseUrl}ph.png`,
    PLN: `${flagBaseUrl}pl.png`,
    RON: `${flagBaseUrl}ro.png`,
    SEK: `${flagBaseUrl}se.png`,
    SGD: `${flagBaseUrl}sg.png`,
    THB: `${flagBaseUrl}th.png`,
    TRY: `${flagBaseUrl}tr.png`,
    USD: `${flagBaseUrl}us.png`,
    ZAR: `${flagBaseUrl}za.png`,
};
export default currencyFlags;
